// Recoil
export const RECOIL_SEARCH_ACCOUNT = "RECOIL_SEARCH_ACCOUNT";
export const RECOIL_CONNECTED_ACCOUNT = "RECOIL_CONNECTED_ACCOUNT";
export const RECOIL_GENERATED_AUTH_TOKEN = "RECOIL_GENERATED_AUTH_TOKEN";
export const RECOIL_API_KEY_INFO = "RECOIL_API_KEY_INFO";

// React-Query
// query
export const QUERY_ACCOUNT_BALANCE = "QUERY_ACCOUNT_BALANCE";
export const QUERY_NFT_BY_OWNER = "QUERY_NFT_BY_OWNER";
export const QUERY_NFT_METADATA_BY_TOKEN_ID = "QUERY_NFT_METADATA_BY_TOKEN_ID";
export const QUERY_ACCOUNT_TRANSACTIONS = "QUERY_ACCOUNT_TRANSACTIONS";
export const GET_AUTH_TOKEN = "GET_AUTH_TOKEN";

// mutation
export const CREATE_AUTH_TOKEN = "CREATE_AUTH_TOKEN";
