// Recoil
export const RECOIL_SEARCH_ACCOUNT = "RECOIL_SEARCH_ACCOUNT";
export const RECOIL_CONNECTED_ACCOUNT = "RECOIL_CONNECTED_ACCOUNT";

// React-Query
export const QUERY_ACCOUNT_BALANCE = "QUERY_ACCOUNT_BALANCE";
export const QUERY_NFT_BY_OWNER = "QUERY_NFT_BY_OWNER";
export const QUERY_NFT_METADATA_BY_TOKEN_ID = "QUERY_NFT_METADATA_BY_TOKEN_ID";
export const QUERY_ACCOUNT_TRANSACTIONS = "QUERY_ACCOUNT_TRANSACTIONS";
